-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 04:11:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema enable
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `enable` ;

-- -----------------------------------------------------
-- Schema enable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enable` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `enable` ;

-- -----------------------------------------------------
-- Table `enable`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`category` (
  `id` INT NOT NULL,
  `category_description` VARCHAR(100) NOT NULL,
  `parent_category_id` INT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`customer` (
  `id` INT NOT NULL,
  `customer_name` VARCHAR(50) NOT NULL,
  `isCompany` TINYINT(1) NOT NULL,
  `customer_since` DATE NOT NULL,
  `address_1` VARCHAR(50) NOT NULL,
  `address_2` VARCHAR(50) NOT NULL,
  `district` VARCHAR(50) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`invoice` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`invoice` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `customer_id` INT NOT NULL,
  `invoice_total` FLOAT NOT NULL,
  `sales_tax_rate` FLOAT NOT NULL,
  `sales_tax_amount` FLOAT NOT NULL,
  `grand_total` FLOAT NOT NULL,
  `isPaid` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `customer_invoice`
    FOREIGN KEY (`customer_id`)
    REFERENCES `enable`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `customer_invoice_idx` ON `enable`.`invoice` (`customer_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`customerhistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`customerhistory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`customerhistory` (
  `id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  `balance` FLOAT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `customer_history`
    FOREIGN KEY (`customer_id`)
    REFERENCES `enable`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_history_invoice_id`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `enable`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `customer_history_idx` ON `enable`.`customerhistory` (`customer_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `customer_history_invoice_id_idx` ON `enable`.`customerhistory` (`invoice_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`supplier` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`supplier` (
  `id` INT NOT NULL,
  `supplier_name` VARCHAR(50) NOT NULL,
  `supplier_since` DATE NOT NULL,
  `address_1` VARCHAR(50) NOT NULL,
  `address_2` VARCHAR(50) NOT NULL,
  `district` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `website` VARCHAR(50) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`product` (
  `id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `brand_Name` VARCHAR(50) NOT NULL,
  `model_number` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `isTaxable` TINYINT(1) NOT NULL,
  `isActive` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `enable`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supplier_product`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `enable`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `product_category_idx` ON `enable`.`product` (`category_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `supplier_product_idx` ON `enable`.`product` (`supplier_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`invoice_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`invoice_detail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`invoice_detail` (
  `id` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `line_total` FLOAT NOT NULL,
  `isTaxable` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `invoice_detail`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `enable`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `enable`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `invoice_detail_idx` ON `enable`.`invoice_detail` (`invoice_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `invoice_detail_product_idx` ON `enable`.`invoice_detail` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`pricehistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`pricehistory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`pricehistory` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `price_date` DATE NOT NULL,
  `price_bought` FLOAT NOT NULL,
  `price_sold` FLOAT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_price_history`
    FOREIGN KEY (`product_id`)
    REFERENCES `enable`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `product_price_history_idx` ON `enable`.`pricehistory` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`productdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`productdetail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`productdetail` (
  `id` INT NOT NULL,
  `detail_name` VARCHAR(50) NOT NULL,
  `detail_value` VARCHAR(50) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `product_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_detail`
    FOREIGN KEY (`product_id`)
    REFERENCES `enable`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `product_detail_idx` ON `enable`.`productdetail` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`purchase_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`purchase_order` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`purchase_order` (
  `id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `supplier_id` INT NOT NULL,
  `order_total` FLOAT NOT NULL,
  `tax_rate` FLOAT NOT NULL,
  `tax_amount` FLOAT NOT NULL,
  `grand_total` FLOAT NOT NULL,
  `isPaid` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `supplier_purchase_order`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `enable`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `supplier_purchase_order_idx` ON `enable`.`purchase_order` (`supplier_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`purchaseorderdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`purchaseorderdetail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`purchaseorderdetail` (
  `id` INT NOT NULL,
  `purchase_order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `line_total` FLOAT NOT NULL,
  `isTaxable` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `purchase_order_detail`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `enable`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_purchase_order_detail`
    FOREIGN KEY (`product_id`)
    REFERENCES `enable`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `purchase_order_detail_idx` ON `enable`.`purchaseorderdetail` (`purchase_order_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `product_purchase_order_detail_idx` ON `enable`.`purchaseorderdetail` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enable`.`supplierhistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enable`.`supplierhistory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enable`.`supplierhistory` (
  `id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `payment_date` DATE NOT NULL,
  `purchase_order_id` INT NOT NULL,
  `payment_amount` FLOAT NOT NULL,
  `balance_due` DATE NOT NULL,
  `paidInFull` TINYINT(1) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `supplier_history`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `enable`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supplier_history_purchase_order`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `enable`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `supplier_history_idx` ON `enable`.`supplierhistory` (`supplier_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `supplier_history_purchase_order_idx` ON `enable`.`supplierhistory` (`purchase_order_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
